### ISSUE TITLE
有关CUB200

### ISSUE THREAD

**Issue by sorrowyn** [milkxie/SPML-LAC#2]
你好，方便提供cub的训练配置文件嘛？
以下是我的训练日志文件

```python
[04/01 19:47:34.705]: ==========================================
[04/01 19:47:34.705]: ==========       CONFIG      =============
[04/01 19:47:34.705]: ==========================================
[04/01 19:47:34.705]: dataset_name: CUB_200_2011
[04/01 19:47:34.705]: dataset_dir: /media/data2/MLICdataset/
[04/01 19:47:34.705]: img_size: 448
[04/01 19:47:34.705]: output: ./checkpoint/Partial-SPML-LAC/ResNet50_448_CUB_200_2011/work1/CUB_200_2011/first
[04/01 19:47:34.706]: num_class: 312
[04/01 19:47:34.706]: stage: first
[04/01 19:47:34.706]: arch: LEM-R50-448
[04/01 19:47:34.706]: config: None
[04/01 19:47:34.706]: loss_mode: bce
[04/01 19:47:34.706]: lambda_plc: 1.0
[04/01 19:47:34.707]: lambda_lac: 1
[04/01 19:47:34.707]: threshold: 0.5
[04/01 19:47:34.707]: temperature: 0.5
[04/01 19:47:34.707]: queue_size: 512
[04/01 19:47:34.707]: loss_dev: -1
[04/01 19:47:34.707]: n_holes: 1
[04/01 19:47:34.707]: length: 224
[04/01 19:47:34.707]: cut_fact: 0.5
[04/01 19:47:34.707]: optim: AdamW
[04/01 19:47:34.707]: lr_scheduler: OneCycleLR
[04/01 19:47:34.707]: pattern_parameters: single_lr
[04/01 19:47:34.707]: momentum: 0.9
[04/01 19:47:34.707]: warmup_epoch: 0
[04/01 19:47:34.707]: warmup_scheduler: False
[04/01 19:47:34.707]: epoch_step: [10, 20]
[04/01 19:47:34.707]: workers: 16
[04/01 19:47:34.707]: epochs: 40
[04/01 19:47:34.707]: val_interval: 1
[04/01 19:47:34.707]: start_epoch: 0
[04/01 19:47:34.707]: batch_size: 32
[04/01 19:47:34.707]: lr: 0.0001
[04/01 19:47:34.707]: weight_decay: 0.01
[04/01 19:47:34.707]: print_freq: 400
[04/01 19:47:34.707]: amp: True
[04/01 19:47:34.707]: early_stop: True
[04/01 19:47:34.707]: world_size: 2
[04/01 19:47:34.707]: rank: 0
[04/01 19:47:34.708]: dist_url: tcp://127.0.0.1:3718
[04/01 19:47:34.708]: seed: 1
[04/01 19:47:34.708]: local_rank: 0
[04/01 19:47:34.708]: use_BN: False
[04/01 19:47:34.708]: enc_layers: 1
[04/01 19:47:34.708]: dec_layers: 2
[04/01 19:47:34.708]: dim_feedforward: 8192
[04/01 19:47:34.708]: hidden_dim: 2048
[04/01 19:47:34.708]: dropout: 0.1
[04/01 19:47:34.708]: nheads: 4
[04/01 19:47:34.708]: pre_norm: False
[04/01 19:47:34.708]: position_embedding: v2
[04/01 19:47:34.708]: keep_other_self_attn_dec: False
[04/01 19:47:34.708]: keep_first_self_attn_dec: False
[04/01 19:47:34.708]: keep_input_proj: False
[04/01 19:47:34.708]: backbone: resnet50
[04/01 19:47:34.708]: pretrained: True
[04/01 19:47:34.708]: feat_dim: 128
[04/01 19:47:34.708]: is_proj: False
[04/01 19:47:34.708]: evaluate: False
[04/01 19:47:34.708]: resume:
[04/01 19:47:34.708]: resume_omit: []
[04/01 19:47:34.708]: ema_decay: 0.9997
[04/01 19:47:34.708]: ema_epoch: 0
[04/01 19:47:34.708]: out_aps: False
[04/01 19:47:34.708]: gpus: 0,1
[04/01 19:47:34.708]: device: cuda
[04/01 19:47:34.708]: ==========================================
[04/01 19:47:34.708]: ===========        END        ============
[04/01 19:47:34.708]: ==========================================
[04/01 19:47:34.708]:

pretrainedpath file is exist.
load pretrained done.
set model.input_proj to Indentify!
[04/01 19:47:39.656]: number of params:175585592
[04/01 19:47:39.657]: params:
{
  "module.backbone.0.body.layer2.0.conv1.weight": 32768,
  "module.backbone.0.body.layer2.0.conv2.weight": 147456,
  "module.backbone.0.body.layer2.0.conv3.weight": 65536,
  "module.backbone.0.body.layer2.0.downsample.0.weight": 131072,
  "module.backbone.0.body.layer2.1.conv1.weight": 65536,
  "module.backbone.0.body.layer2.1.conv2.weight": 147456,
  "module.backbone.0.body.layer2.1.conv3.weight": 65536,
  "module.backbone.0.body.layer2.2.conv1.weight": 65536,
  "module.backbone.0.body.layer2.2.conv2.weight": 147456,
  "module.backbone.0.body.layer2.2.conv3.weight": 65536,
  "module.backbone.0.body.layer2.3.conv1.weight": 65536,
  "module.backbone.0.body.layer2.3.conv2.weight": 147456,
  "module.backbone.0.body.layer2.3.conv3.weight": 65536,
  "module.backbone.0.body.layer3.0.conv1.weight": 131072,
  "module.backbone.0.body.layer3.0.conv2.weight": 589824,
  "module.backbone.0.body.layer3.0.conv3.weight": 262144,
  "module.backbone.0.body.layer3.0.downsample.0.weight": 524288,
  "module.backbone.0.body.layer3.1.conv1.weight": 262144,
  "module.backbone.0.body.layer3.1.conv2.weight": 589824,
  "module.backbone.0.body.layer3.1.conv3.weight": 262144,
  "module.backbone.0.body.layer3.2.conv1.weight": 262144,
  "module.backbone.0.body.layer3.2.conv2.weight": 589824,
  "module.backbone.0.body.layer3.2.conv3.weight": 262144,
  "module.backbone.0.body.layer3.3.conv1.weight": 262144,
  "module.backbone.0.body.layer3.3.conv2.weight": 589824,
  "module.backbone.0.body.layer3.3.conv3.weight": 262144,
  "module.backbone.0.body.layer3.4.conv1.weight": 262144,
  "module.backbone.0.body.layer3.4.conv2.weight": 589824,
  "module.backbone.0.body.layer3.4.conv3.weight": 262144,
  "module.backbone.0.body.layer3.5.conv1.weight": 262144,
  "module.backbone.0.body.layer3.5.conv2.weight": 589824,
  "module.backbone.0.body.layer3.5.conv3.weight": 262144,
  "module.backbone.0.body.layer4.0.conv1.weight": 524288,
  "module.backbone.0.body.layer4.0.conv2.weight": 2359296,
  "module.backbone.0.body.layer4.0.conv3.weight": 1048576,
  "module.backbone.0.body.layer4.0.downsample.0.weight": 2097152,
  "module.backbone.0.body.layer4.1.conv1.weight": 1048576,
  "module.backbone.0.body.layer4.1.conv2.weight": 2359296,
  "module.backbone.0.body.layer4.1.conv3.weight": 1048576,
  "module.backbone.0.body.layer4.2.conv1.weight": 1048576,
  "module.backbone.0.body.layer4.2.conv2.weight": 2359296,
  "module.backbone.0.body.layer4.2.conv3.weight": 1048576,
  "module.encoder.encoder.layers.0.self_attn.in_proj_weight": 12582912,
  "module.encoder.encoder.layers.0.self_attn.in_proj_bias": 6144,
  "module.encoder.encoder.layers.0.self_attn.out_proj.weight": 4194304,
  "module.encoder.encoder.layers.0.self_attn.out_proj.bias": 2048,
  "module.encoder.encoder.layers.0.linear1.weight": 16777216,
  "module.encoder.encoder.layers.0.linear1.bias": 8192,
  "module.encoder.encoder.layers.0.linear2.weight": 16777216,
  "module.encoder.encoder.layers.0.linear2.bias": 2048,
  "module.encoder.encoder.layers.0.norm1.weight": 2048,
  "module.encoder.encoder.layers.0.norm1.bias": 2048,
  "module.encoder.encoder.layers.0.norm2.weight": 2048,
  "module.encoder.encoder.layers.0.norm2.bias": 2048,
  "module.encoder.decoder.layers.0.multihead_attn.in_proj_weight": 12582912,
  "module.encoder.decoder.layers.0.multihead_attn.in_proj_bias": 6144,
  "module.encoder.decoder.layers.0.multihead_attn.out_proj.weight": 4194304,
  "module.encoder.decoder.layers.0.multihead_attn.out_proj.bias": 2048,
  "module.encoder.decoder.layers.0.linear1.weight": 16777216,
  "module.encoder.decoder.layers.0.linear1.bias": 8192,
  "module.encoder.decoder.layers.0.linear2.weight": 16777216,
  "module.encoder.decoder.layers.0.linear2.bias": 2048,
  "module.encoder.decoder.layers.0.norm2.weight": 2048,
  "module.encoder.decoder.layers.0.norm2.bias": 2048,
  "module.encoder.decoder.layers.0.norm3.weight": 2048,
  "module.encoder.decoder.layers.0.norm3.bias": 2048,
  "module.encoder.decoder.layers.1.multihead_attn.in_proj_weight": 12582912,
  "module.encoder.decoder.layers.1.multihead_attn.in_proj_bias": 6144,
  "module.encoder.decoder.layers.1.multihead_attn.out_proj.weight": 4194304,
  "module.encoder.decoder.layers.1.multihead_attn.out_proj.bias": 2048,
  "module.encoder.decoder.layers.1.linear1.weight": 16777216,
  "module.encoder.decoder.layers.1.linear1.bias": 8192,
  "module.encoder.decoder.layers.1.linear2.weight": 16777216,
  "module.encoder.decoder.layers.1.linear2.bias": 2048,
  "module.encoder.decoder.layers.1.norm2.weight": 2048,
  "module.encoder.decoder.layers.1.norm2.bias": 2048,
  "module.encoder.decoder.layers.1.norm3.weight": 2048,
  "module.encoder.decoder.layers.1.norm3.bias": 2048,
  "module.query_embed.weight": 638976,
  "module.fc.W": 638976,
  "module.fc.b": 312
}
[04/01 19:47:39.657]: lr: 1.25e-05
[04/01 19:47:39.680]: len(train_dataset): 4795
[04/01 19:47:39.680]: len(val_dataset): 1199
[04/01 19:47:39.680]: len(test_dataset): 5794
[04/01 19:47:39.729]: lr:5.000000000000003e-07
[04/01 19:47:48.410]: Epoch: [0/40][  0/149]  T 8.680 (8.680)  DT 4.470 (4.470)  S1 3.7 (3.7)  SA 7.4 (7.4)  LR 5.000e-07  L_an 0.740 (0.740)  L_plc 0                                                   .565 (0.565)  Loss 1.305 (1.305)  Mem 10670
[04/01 19:49:22.728]: Test: [ 0/38]  Time 2.021 (2.021)  Loss 0.368 (0.368)  Mem 11641
[04/01 19:49:26.030]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  0.31  3.02  0.44  7.08  2.16  3.30
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  0.21  1.15  0.25  10.97  1.04  1.91
[04/01 19:49:27.962]:   mAP: 11.458297677615318
[04/01 19:49:29.781]: Test: [ 0/38]  Time 1.817 (1.817)  Loss 0.740 (0.740)  Mem 11641
[04/01 19:49:32.881]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  9.43  48.22  10.86  8.85  42.76  14.67
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  2.39  0.98  0.49  6.00  0.57  1.04
[04/01 19:49:35.783]:   mAP: 11.480101812936208
[04/01 19:49:35.784]: => Test Epoch: [ 0/40]  ETA 1:15:28  TT 0:01:56 (0:01:56)  Loss 0.393  mAP 11.45830  Loss_ema 0.734  mAP_ema 11.48010
[04/01 19:49:38.065]: Test: [  0/182]  Time 2.279 (2.279)  Loss 0.739 (0.739)  Mem 11641
[04/01 19:49:52.758]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  9.81  49.11  11.13  8.88  42.99  14.72
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  2.49  0.88  0.40  5.56  0.53  0.97
[04/01 19:50:06.777]:   mAP: 10.875230844658773
[04/01 19:50:06.777]: 0 | Set best mAP 11.480101812936208 in ep 0
[04/01 19:50:06.777]:    | best regular mAP 11.458297677615318 in ep 0
[04/01 19:50:06.777]:    | best test mAP in test 10.875230844658773
[04/01 19:50:12.977]: lr:9.574801814685072e-07
[04/01 19:50:15.913]: Epoch: [1/40][  0/149]  T 2.935 (2.935)  DT 1.278 (1.278)  S1 10.9 (10.9)  SA 21.8 (21.8)  LR 9.636e-07  L_an 0.283 (0.283)  L_plc 0.272 (0.272)  Loss 0.556 (0.556)  Mem 11653
[04/01 19:51:51.380]: Test: [ 0/38]  Time 2.087 (2.087)  Loss 0.279 (0.279)  Mem 11660
[04/01 19:51:54.387]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  0.00  0.00  0.00  nan  0.00  nan
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  0.00  0.00  0.00  nan  0.00  nan
[04/01 19:51:56.067]:   mAP: 11.509943406752559
[04/01 19:51:57.419]: Test: [ 0/38]  Time 1.351 (1.351)  Loss 0.712 (0.712)  Mem 11660
[04/01 19:52:00.962]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  9.36  43.64  10.10  8.69  37.99  14.15
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  2.31  1.01  0.47  5.89  0.56  1.02
[04/01 19:52:02.928]:   mAP: 11.472811524207922
[04/01 19:52:02.928]: => Test Epoch: [ 1/40]  ETA 1:23:21  TT 0:02:27 (0:04:23)  Loss 0.343  mAP 11.50994  Loss_ema 0.707  mAP_ema 11.47281
[04/01 19:52:02.930]: Start test in model
[04/01 19:52:04.800]: Test: [  0/182]  Time 1.869 (1.869)  Loss 0.305 (0.305)  Mem 11660
[04/01 19:52:19.313]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  10.04  22.29  8.09  8.73  19.12  11.99
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  2.41  0.46  0.29  5.67  0.27  0.52
[04/01 19:52:29.846]:   mAP: 10.722179358990038
[04/01 19:52:29.847]: 1 | Set best mAP 11.509943406752559 in ep 1
[04/01 19:52:29.847]:    | best regular mAP 11.509943406752559 in ep 1
[04/01 19:52:29.847]:    | best test mAP in test 10.722179358990038
[04/01 19:52:34.038]: lr:2.2601580203952075e-06
[04/01 19:52:36.911]: Epoch: [2/40][  0/149]  T 2.873 (2.873)  DT 2.000 (2.000)  S1 11.1 (11.1)  SA 22.3 (22.3)  LR 2.271e-06  L_an 0.082 (0.082)  L_plc 0.083 (0.083)  Loss 0.165 (0.165)  Mem 11660
[04/01 19:54:11.279]: Test: [ 0/38]  Time 1.365 (1.365)  Loss 0.392 (0.392)  Mem 11660
[04/01 19:54:14.953]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  0.00  0.00  0.00  nan  0.00  nan
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  0.00  0.00  0.00  nan  0.00  nan
[04/01 19:54:18.211]:   mAP: 11.536338526245395
[04/01 19:54:20.197]: Test: [ 0/38]  Time 1.984 (1.984)  Loss 0.685 (0.685)  Mem 11660
[04/01 19:54:23.300]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  9.54  39.26  9.41  8.58  33.49  13.66
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  1.98  1.01  0.44  6.00  0.57  1.04
[04/01 19:54:26.057]:   mAP: 11.496582030925525
[04/01 19:54:26.058]: => Test Epoch: [ 2/40]  ETA 1:23:31  TT 0:02:23 (0:06:46)  Loss 0.500  mAP 11.53634  Loss_ema 0.680  mAP_ema 11.49658
[04/01 19:54:26.060]: Start test in model
[04/01 19:54:27.844]: Test: [  0/182]  Time 1.783 (1.783)  Loss 0.439 (0.439)  Mem 11660
[04/01 19:54:42.585]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  9.69  19.79  7.37  8.57  16.74  11.34
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  2.09  0.46  0.28  5.57  0.26  0.51
[04/01 19:54:51.708]:   mAP: 10.711641131383535
[04/01 19:54:51.708]: 2 | Set best mAP 11.536338526245395 in ep 2
[04/01 19:54:51.708]:    | best regular mAP 11.536338526245395 in ep 2
[04/01 19:54:51.709]:    | best test mAP in test 10.711641131383535
[04/01 19:54:55.938]: lr:4.209383752064371e-06
[04/01 19:54:58.857]: Epoch: [3/40][  0/149]  T 2.919 (2.919)  DT 1.274 (1.274)  S1 11.0 (11.0)  SA 21.9 (21.9)  LR 4.224e-06  L_an 0.024 (0.024)  L_plc 0.024 (0.024)  Loss 0.047 (0.047)  Mem 11660
[04/01 19:56:32.691]: Test: [ 0/38]  Time 1.746 (1.746)  Loss 0.428 (0.428)  Mem 11660
[04/01 19:56:36.089]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  0.00  0.00  0.00  nan  0.00  nan
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  0.00  0.00  0.00  nan  0.00  nan
[04/01 19:56:39.316]:   mAP: 11.534806507164129
[04/01 19:56:40.944]: Test: [ 0/38]  Time 1.626 (1.626)  Loss 0.657 (0.657)  Mem 11660
[04/01 19:56:44.424]: => synchronize...
Calculating mAP:
 *    CP     CR     CF     OP     OR     OF
 *  9.21  34.32  8.51  8.45  28.99  13.09
 *   CP3    CR3    CF3    OP3    OR3    OF3
 *  2.33  0.90  0.38  5.86  0.56  1.02
[04/01 19:56:46.905]:   mAP: 11.457726410821463
[04/01 19:56:46.905]: => Test Epoch: [ 3/40]  ETA 1:22:05  TT 0:02:20 (0:09:07)  Loss 0.547  mAP 11.53481  Loss_ema 0.652  mAP_ema 11.45773
[04/01 19:56:46.907]: 3 | Set best mAP 11.536338526245395 in ep 2
[04/01 19:56:46.907]:    | best regular mAP 11.536338526245395 in ep 2
[04/01 19:56:46.907]:    | best test mAP in test 10.711641131383535
[04/01 19:56:46.989]: lr:6.5079133293269695e-06
^[zqTraceback (most recent call last):
  File "/media/data/maleilei/MLIC/SPML-LAC/main_mlc.py", line 50, in <module>
    main()
  File "/media/data/maleilei/MLIC/SPML-LAC/main_mlc.py", line 42, in main
    return main_worker_first_stage(args, logger)
  File "/media/data/maleilei/MLIC/SPML-LAC/all_lib/lib_modifiy/main_worker_first_stage.py", line 250, in main_worker_first_stage
    _, mAP_ema_test = validate(test_loader, ema_m.module, criterion, args, logger)
  File "/home/mll/anaconda3/envs/torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/data/maleilei/MLIC/SPML-LAC/all_lib/lib_modifiy/engine_first_stage.py", line 154, in validate
    dist.barrier()
  File "/home/mll/anaconda3/envs/torch/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2783, in barrier
    work.wait()
RuntimeError: [/opt/conda/conda-bld/pytorch_1646756402876/work/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:3981
```

**Comment by xiemk** [comment]
不好意思，github好像没提醒，没注意到~

first_stage_config:
`{
  "dataname": "cub",
  "dataset_dir": "",
  "x_u_ratio": 9,
  "mu": 9,
  "img_size": 448,
  "output": "",
  "num_class": 312,
  "pretrained": true,
  "optim": "AdamW",
  "arch": "Q2L-R101-448",
  "lambda_u": 1,
  "threshold": 0.5,
  "eps": 1e-05,
  "dtgfl": false,
  "gamma_pos": 0,
  "gamma_neg": 2,
  "loss_dev": -1,
  "loss_clip": 0.0,
  "workers": 32,
  "epochs": 40,
  "val_interval": 1,
  "start_epoch": 0,
  "batch_size": 32,
  "lr": 0.0001,
  "weight_decay": 0.01,
  "print_freq": 100,
  "resume": "",
  "resume_omit": [],
  "evaluate": false,
  "ema_decay": 0.9997,
  "ema_epoch": -1,
  "world_size": 1,
  "rank": 0,
  "dist_url": "env://",
  "seed": 1,
  "local_rank": null,
  "cutout": false,
  "n_holes": 1,
  "length": -1,
  "cut_fact": 0.5,
  "orid_norm": false,
  "enc_layers": 1,
  "dec_layers": 2,
  "dim_feedforward": 8192,
  "hidden_dim": 2048,
  "feat_dim": 128,
  "is_proj": false,
  "dropout": 0.1,
  "nheads": 4,
  "pre_norm": false,
  "position_embedding": "sine",
  "backbone": "resnet50",
  "keep_other_self_attn_dec": false,
  "keep_first_self_attn_dec": false,
  "keep_input_proj": false,
  "amp": true,
  "early_stop": true,
  "kill_stop": false
}`

second_stage_config:
`{
  "dataname": "cub",
  "dataset_dir": "",
  "x_u_ratio": 9,
  "mu": 9,
  "img_size": 448,
  "output": "",
  "num_class": 312,
  "pretrained": true,
  "optim": "AdamW",
  "arch": "Q2L-R101-448",
  "queue_size": 4096,
  "contrast_temp": 0.1,
  "contrast_th": 0.9,
  "threshold": 0.9,
  "lambda_u": 1,
  "lambda_c": 1,
  "eps": 1e-05,
  "dtgfl": false,
  "gamma_pos": 0,
  "gamma_neg": 2,
  "loss_dev": -1,
  "loss_clip": 0.0,
  "workers": 32,
  "epochs": 40,
  "val_interval": 1,
  "start_epoch": 0,
  "batch_size": 8,
  "lr": 0.0001,
  "weight_decay": 0.01,
  "print_freq": 100,
  "resume": "",
  "resume_omit": [],
  "evaluate": false,
  "ema_decay": 0.9997,
  "ema_epoch": -1,
  "world_size": 1,
  "rank": 0,
  "dist_url": "env://",
  "seed": 1,
  "local_rank": null,
  "cutout": false,
  "n_holes": 1,
  "length": -1,
  "cut_fact": 0.5,
  "orid_norm": false,
  "enc_layers": 1,
  "dec_layers": 2,
  "dim_feedforward": 8192,
  "hidden_dim": 2048,
  "feat_dim": 128,
  "is_proj": true,
  "dropout": 0.1,
  "nheads": 4,
  "pre_norm": false,
  "position_embedding": "sine",
  "backbone": "resnet50",
  "keep_other_self_attn_dec": false,
  "keep_first_self_attn_dec": false,
  "keep_input_proj": false,
  "amp": true,
  "early_stop": true,
  "kill_stop": false
}`

**Comment by sorrowyn** [comment]
感谢你提供的配置文件，目前我还有两个小问题：
问题1： "x_u_ratio": 9, "mu": 9,。这两个参数是什么，有点不懂。
问题2：为了复现这个实验，能够提供观察的标签文件`formatted_val_labels_obs.npy`，
我的邮箱：xiaomylei@163.com

**Comment by JiahaoXxX** [comment]
关于两个问题的回答如下：
回答1：这两个参数是为了半监督学习设置的，但在最终上传的代码中未被使用，故删除，并不会影响实验结果，忽略即可。不好意思给您造成了困扰。
回答2：观察标签文件`formatted_val_labels_obs.npy`可以通过`preproc/generate_observed_labels.py`生成。（需要的文件已发送至邮箱）
